#!/bin/sh -e

make mrproper
make HOSTCC="$CC" headers

find usr/include -name \*.h -type f |
    while read -r file; do
        mkdir -p "$1/cross/${LFS_TARGET}/${file%/*}"
        cp -f "$file" "$1/cross/${LFS_TARGET}/$file"
    done
