#!/bin/sh -e

:> nostrip

sed -i s/mawk// configure

mkdir build
pushd build
    ../configure
    make -C include
    make -C progs tic
popd

./configure \
    --prefix="/usr" \
    --host="$KISS_TGT" \
    --build="$(./config.guess)" \
    --mandir="/usr/share/man" \
    --with-manpage-format=normal \
    --with-shared \
    --without-normal \
    --with-cxx-shared \
    --without-debug \
    --without-ada \
    --disable-stripping \
    --enable-widec

make
make TIC_PATH="$(pwd)/build/progs/tic" install
echo "INPUT(-lncursesw)" > "$1/usr/lib/libncurses.so"
