#!/bin/sh -e

mkdir -p build && cd build

../configure \
    --prefix="/tools" \
    --with-sysroot="$KISS_ROOT" \
    --target="$KISS_TGT" \
    --disable-nls \
    --enable-gprofng=no \
    --disable-werror

make
make install
