#!/bin/sh -e

case $(uname -m) in
    x86_64)
        sed -e '/m64=/s/lib64/lib/' \
            -i.orig gcc/config/i386/t-linux64
        ;;
esac

sed '/thread_header =/s/@.*@/gthr-posix.h/' \
    -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir -p build && cd build

../configure \
    --build="$(../config.guess)" \
    --host="$KISS_TGT" \
    --target="$KISS_TGT" \
    LDFLAGS_FOR_TARGET=-L$PWD/$KISS_TGT/libgcc \
    --prefix="/usr" \
    --with-build-sysroot="$KISS_ROOT" \
    --enable-initfini-array \
    --disable-nls \
    --disable-multilib \
    --disable-decimal-float \
    --disable-libatomic \
    --disable-libgomp \
    --disable-libquadmath \
    --disable-libssp \
    --disable-libvtv \
    --enable-languages=c,c++

make
make install

mkdir -p "$1/usr/bin"
ln -sv gcc "$1/usr/bin/cc"
