#!/bin/sh -e

mkdir -p build && cd build

../configure \
    --prefix="/usr" \
    --host="$KISS_TGT" \
    --build=$(../scripts/config.guess) \
    --enable-kernel=3.2 \
    --with-headers="$KISS_ROOT/usr/include" \
    libc_cv_slibdir=/usr/lib

make
make install

sed '/RTLDLIST=/s@/usr@@g' -i "$1/usr/bin/ldd"
