#!/bin/sh -e

mkdir -p "$1/"{lib,lib64}
case $(uname -m) in
    i?86)
        ln -sfv ld-linux.so.2 "$1/lib/ld-lsb.so.3"
        ;;
    x86_64)
        ln -sfv ../lib/ld-linux-x86-64.so.2 "$1/lib64"
        ln -sfv ../lib/ld-linux-x86-64.so.2 "$1/lib64/ld-lsb-x86-64.so.3"
        ;;
esac

mkdir -p build && cd build

../configure \
    --prefix="/usr" \
    --host="$KISS_TGT" \
    --build=$(../scripts/config.guess) \
    --enable-kernel=3.2 \
    --with-headers="$KISS_ROOT/usr/include" \
    libc_cv_slibdir=/usr/lib

make
make install

sed '/RTLDLIST=/s@/usr@@g' -i "$1/usr/bin/ldd"
