#!/bin/sh -e

unset DESTDIR

sh Configure \
    -des \
    -Dprefix=/usr \
    -Dvendorprefix=/usr \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dprivlib=/usr/lib/perl5/$2/core_perl \
    -Darchlib=/usr/lib/perl5/$2/core_perl \
    -Dsitelib=/usr/lib/perl5/$2/site_perl \
    -Dsitearch=/usr/lib/perl5/$2/site_perl \
    -Dvendorlib=/usr/lib/perl5/$2/vendor_perl \
    -Dvendorarch=/usr/lib/perl5/$2/vendor_perl

make
make DESTDIR="$1" install
