#!/bin/sh -e

mkdir -p build
pushd build
    ../configure \
        --disable-bzlib \
        --disable-libseccomp \
        --disable-xzlib \
        --disable-zlib
    make
popd

./configure \
    --prefix="/usr" \
    --host="$KISS_TGT" \
    --build="$(./config.guess)" \
    --disable-zlib

make FILE_COMPILE="$(pwd)/build/src/file"
make install

rm -v "$1/usr/lib/libmagic.la"
